# This file specifies a mapping of environment variables to config properties - keys are config names, while the
# values are the names of the environment variables that override the associated config.
#
# e.g.
#
# foo:
#   bar: MY_CUSTOM_VAR
#
# means that if the env var "MY_CUSTOM_VAR" is set, it will override the value of the config "foo.bar" - if it isn't
# set, the value of the "foo.bar" config will be determined from the .yml files as usual.

appEnv:         APP_ENV

isDevelopment:
  __name: IS_DEVELOPMENT
  __format: json

portFE:         PORT_FRONTEND
portHMR:        PORT_HMR
portBSProxy:    PORT_BS_PROXY
portBSUI:       PORT_BS_UI
