appEnv:         development
isDevelopment:  true
debug:          true

ports:
  portFE:         7000
  portHMR:        7070
  portBSProxy:    7001
  portBSUI:       3000

api:
    # refactor: run api on other port!?
    # uses portFE (until we have portAPI)
    base:           http://localhost:7000/api
    endpoints:
        items:      '/items'
